# Generated by Django 2.2 on 2019-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Organism', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveIntegerField()),
                ('Domain', models.CharField(max_length=200)),
                ('Mode', models.CharField(max_length=200)),
            ],
        ),
    ]
